export const GET_LIST_ORDER = "[ORDER] GET LIST ORDER";
export const GET_LIST_ORDER_BY_UID = "[ORDER] GET USER LIST ORDER";
export const CREATE_ORDER = "[ORDER] CREATE ORDER";
export const GET_ORDER_BY_ID = "[ORDER] GET ORDER BY ID";
export const UPDATE_ORDER = "[ORDER] UPDATE ORDER";
